apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-dev
  artifacts:
    - image: fpagnamenta/auth
      # image: us.gcr.io/ticketing-dev-300615/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: fpagnamenta/client
      # image: us.gcr.io/ticketing-dev-300615/auth
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: fpagnamenta/tickets
      # image: us.gcr.io/ticketing-dev-300615/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: fpagnamenta/orders
      # image: us.gcr.io/ticketing-dev-300615/tickets
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: fpagnamenta/payments
      # image: us.gcr.io/ticketing-dev-300615/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: fpagnamenta/expiration
      # image: us.gcr.io/ticketing-dev-300615/tickets
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
